/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWarehousesRouteImport } from './routes/_authenticated/warehouses'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCashSessionsRouteImport } from './routes/_authenticated/cash-sessions'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedSalesIndexRouteImport } from './routes/_authenticated/sales.index'
import { Route as AuthenticatedReturnsIndexRouteImport } from './routes/_authenticated/returns.index'
import { Route as AuthenticatedPurchaseOrdersIndexRouteImport } from './routes/_authenticated/purchase-orders.index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products.index'
import { Route as AuthenticatedMovementsIndexRouteImport } from './routes/_authenticated/movements.index'
import { Route as AuthenticatedDisbursementIndexRouteImport } from './routes/_authenticated/disbursement.index'
import { Route as AuthenticatedDestockingIndexRouteImport } from './routes/_authenticated/destocking.index'
import { Route as AuthenticatedDefectiveIndexRouteImport } from './routes/_authenticated/defective.index'
import { Route as AuthenticatedBillingIndexRouteImport } from './routes/_authenticated/billing.index'
import { Route as AuthenticatedSalesIdRouteImport } from './routes/_authenticated/sales.$id'
import { Route as AuthenticatedReturnsNewRouteImport } from './routes/_authenticated/returns.new'
import { Route as AuthenticatedPurchaseOrdersNewRouteImport } from './routes/_authenticated/purchase-orders.new'
import { Route as AuthenticatedPurchaseOrdersIdRouteImport } from './routes/_authenticated/purchase-orders.$id'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products.new'
import { Route as AuthenticatedProductsIdRouteImport } from './routes/_authenticated/products.$id'
import { Route as AuthenticatedMovementsNewRouteImport } from './routes/_authenticated/movements.new'
import { Route as AuthenticatedDisbursementNewRouteImport } from './routes/_authenticated/disbursement.new'
import { Route as AuthenticatedDestockingNewRouteImport } from './routes/_authenticated/destocking.new'
import { Route as AuthenticatedDefectiveNewRouteImport } from './routes/_authenticated/defective.new'
import { Route as AuthenticatedBillingSettingsRouteImport } from './routes/_authenticated/billing.settings'
import { Route as AuthenticatedBillingNewRouteImport } from './routes/_authenticated/billing.new'
import { Route as AuthenticatedBillingIdRouteImport } from './routes/_authenticated/billing.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWarehousesRoute = AuthenticatedWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCashSessionsRoute =
  AuthenticatedCashSessionsRouteImport.update({
    id: '/cash-sessions',
    path: '/cash-sessions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesIndexRoute = AuthenticatedSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReturnsIndexRoute =
  AuthenticatedReturnsIndexRouteImport.update({
    id: '/returns/',
    path: '/returns/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersIndexRoute =
  AuthenticatedPurchaseOrdersIndexRouteImport.update({
    id: '/purchase-orders/',
    path: '/purchase-orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMovementsIndexRoute =
  AuthenticatedMovementsIndexRouteImport.update({
    id: '/movements/',
    path: '/movements/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDisbursementIndexRoute =
  AuthenticatedDisbursementIndexRouteImport.update({
    id: '/disbursement/',
    path: '/disbursement/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDestockingIndexRoute =
  AuthenticatedDestockingIndexRouteImport.update({
    id: '/destocking/',
    path: '/destocking/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDefectiveIndexRoute =
  AuthenticatedDefectiveIndexRouteImport.update({
    id: '/defective/',
    path: '/defective/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingIndexRoute =
  AuthenticatedBillingIndexRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesIdRoute = AuthenticatedSalesIdRouteImport.update({
  id: '/sales/$id',
  path: '/sales/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReturnsNewRoute = AuthenticatedReturnsNewRouteImport.update({
  id: '/returns/new',
  path: '/returns/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchaseOrdersNewRoute =
  AuthenticatedPurchaseOrdersNewRouteImport.update({
    id: '/purchase-orders/new',
    path: '/purchase-orders/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersIdRoute =
  AuthenticatedPurchaseOrdersIdRouteImport.update({
    id: '/purchase-orders/$id',
    path: '/purchase-orders/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIdRoute = AuthenticatedProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovementsNewRoute =
  AuthenticatedMovementsNewRouteImport.update({
    id: '/movements/new',
    path: '/movements/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDisbursementNewRoute =
  AuthenticatedDisbursementNewRouteImport.update({
    id: '/disbursement/new',
    path: '/disbursement/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDestockingNewRoute =
  AuthenticatedDestockingNewRouteImport.update({
    id: '/destocking/new',
    path: '/destocking/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDefectiveNewRoute =
  AuthenticatedDefectiveNewRouteImport.update({
    id: '/defective/new',
    path: '/defective/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingSettingsRoute =
  AuthenticatedBillingSettingsRouteImport.update({
    id: '/billing/settings',
    path: '/billing/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingNewRoute = AuthenticatedBillingNewRouteImport.update({
  id: '/billing/new',
  path: '/billing/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingIdRoute = AuthenticatedBillingIdRouteImport.update({
  id: '/billing/$id',
  path: '/billing/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/cash-sessions': typeof AuthenticatedCashSessionsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/pos': typeof AuthenticatedPosRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/billing/$id': typeof AuthenticatedBillingIdRoute
  '/billing/new': typeof AuthenticatedBillingNewRoute
  '/billing/settings': typeof AuthenticatedBillingSettingsRoute
  '/defective/new': typeof AuthenticatedDefectiveNewRoute
  '/destocking/new': typeof AuthenticatedDestockingNewRoute
  '/disbursement/new': typeof AuthenticatedDisbursementNewRoute
  '/movements/new': typeof AuthenticatedMovementsNewRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRoute
  '/purchase-orders/new': typeof AuthenticatedPurchaseOrdersNewRoute
  '/returns/new': typeof AuthenticatedReturnsNewRoute
  '/sales/$id': typeof AuthenticatedSalesIdRoute
  '/billing/': typeof AuthenticatedBillingIndexRoute
  '/defective/': typeof AuthenticatedDefectiveIndexRoute
  '/destocking/': typeof AuthenticatedDestockingIndexRoute
  '/disbursement/': typeof AuthenticatedDisbursementIndexRoute
  '/movements/': typeof AuthenticatedMovementsIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/purchase-orders/': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/returns/': typeof AuthenticatedReturnsIndexRoute
  '/sales/': typeof AuthenticatedSalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/cash-sessions': typeof AuthenticatedCashSessionsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/pos': typeof AuthenticatedPosRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/billing/$id': typeof AuthenticatedBillingIdRoute
  '/billing/new': typeof AuthenticatedBillingNewRoute
  '/billing/settings': typeof AuthenticatedBillingSettingsRoute
  '/defective/new': typeof AuthenticatedDefectiveNewRoute
  '/destocking/new': typeof AuthenticatedDestockingNewRoute
  '/disbursement/new': typeof AuthenticatedDisbursementNewRoute
  '/movements/new': typeof AuthenticatedMovementsNewRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRoute
  '/purchase-orders/new': typeof AuthenticatedPurchaseOrdersNewRoute
  '/returns/new': typeof AuthenticatedReturnsNewRoute
  '/sales/$id': typeof AuthenticatedSalesIdRoute
  '/billing': typeof AuthenticatedBillingIndexRoute
  '/defective': typeof AuthenticatedDefectiveIndexRoute
  '/destocking': typeof AuthenticatedDestockingIndexRoute
  '/disbursement': typeof AuthenticatedDisbursementIndexRoute
  '/movements': typeof AuthenticatedMovementsIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/returns': typeof AuthenticatedReturnsIndexRoute
  '/sales': typeof AuthenticatedSalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/cash-sessions': typeof AuthenticatedCashSessionsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/warehouses': typeof AuthenticatedWarehousesRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/billing/$id': typeof AuthenticatedBillingIdRoute
  '/_authenticated/billing/new': typeof AuthenticatedBillingNewRoute
  '/_authenticated/billing/settings': typeof AuthenticatedBillingSettingsRoute
  '/_authenticated/defective/new': typeof AuthenticatedDefectiveNewRoute
  '/_authenticated/destocking/new': typeof AuthenticatedDestockingNewRoute
  '/_authenticated/disbursement/new': typeof AuthenticatedDisbursementNewRoute
  '/_authenticated/movements/new': typeof AuthenticatedMovementsNewRoute
  '/_authenticated/products/$id': typeof AuthenticatedProductsIdRoute
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRoute
  '/_authenticated/purchase-orders/new': typeof AuthenticatedPurchaseOrdersNewRoute
  '/_authenticated/returns/new': typeof AuthenticatedReturnsNewRoute
  '/_authenticated/sales/$id': typeof AuthenticatedSalesIdRoute
  '/_authenticated/billing/': typeof AuthenticatedBillingIndexRoute
  '/_authenticated/defective/': typeof AuthenticatedDefectiveIndexRoute
  '/_authenticated/destocking/': typeof AuthenticatedDestockingIndexRoute
  '/_authenticated/disbursement/': typeof AuthenticatedDisbursementIndexRoute
  '/_authenticated/movements/': typeof AuthenticatedMovementsIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/purchase-orders/': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/_authenticated/returns/': typeof AuthenticatedReturnsIndexRoute
  '/_authenticated/sales/': typeof AuthenticatedSalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/audit'
    | '/cash-sessions'
    | '/customers'
    | '/dashboard'
    | '/notifications'
    | '/pos'
    | '/suppliers'
    | '/warehouses'
    | '/admin/roles'
    | '/admin/users'
    | '/billing/$id'
    | '/billing/new'
    | '/billing/settings'
    | '/defective/new'
    | '/destocking/new'
    | '/disbursement/new'
    | '/movements/new'
    | '/products/$id'
    | '/products/new'
    | '/purchase-orders/$id'
    | '/purchase-orders/new'
    | '/returns/new'
    | '/sales/$id'
    | '/billing/'
    | '/defective/'
    | '/destocking/'
    | '/disbursement/'
    | '/movements/'
    | '/products/'
    | '/purchase-orders/'
    | '/returns/'
    | '/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/audit'
    | '/cash-sessions'
    | '/customers'
    | '/dashboard'
    | '/notifications'
    | '/pos'
    | '/suppliers'
    | '/warehouses'
    | '/admin/roles'
    | '/admin/users'
    | '/billing/$id'
    | '/billing/new'
    | '/billing/settings'
    | '/defective/new'
    | '/destocking/new'
    | '/disbursement/new'
    | '/movements/new'
    | '/products/$id'
    | '/products/new'
    | '/purchase-orders/$id'
    | '/purchase-orders/new'
    | '/returns/new'
    | '/sales/$id'
    | '/billing'
    | '/defective'
    | '/destocking'
    | '/disbursement'
    | '/movements'
    | '/products'
    | '/purchase-orders'
    | '/returns'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/audit'
    | '/_authenticated/cash-sessions'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/pos'
    | '/_authenticated/suppliers'
    | '/_authenticated/warehouses'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/users'
    | '/_authenticated/billing/$id'
    | '/_authenticated/billing/new'
    | '/_authenticated/billing/settings'
    | '/_authenticated/defective/new'
    | '/_authenticated/destocking/new'
    | '/_authenticated/disbursement/new'
    | '/_authenticated/movements/new'
    | '/_authenticated/products/$id'
    | '/_authenticated/products/new'
    | '/_authenticated/purchase-orders/$id'
    | '/_authenticated/purchase-orders/new'
    | '/_authenticated/returns/new'
    | '/_authenticated/sales/$id'
    | '/_authenticated/billing/'
    | '/_authenticated/defective/'
    | '/_authenticated/destocking/'
    | '/_authenticated/disbursement/'
    | '/_authenticated/movements/'
    | '/_authenticated/products/'
    | '/_authenticated/purchase-orders/'
    | '/_authenticated/returns/'
    | '/_authenticated/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/warehouses': {
      id: '/_authenticated/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AuthenticatedWarehousesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cash-sessions': {
      id: '/_authenticated/cash-sessions'
      path: '/cash-sessions'
      fullPath: '/cash-sessions'
      preLoaderRoute: typeof AuthenticatedCashSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/': {
      id: '/_authenticated/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AuthenticatedSalesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/returns/': {
      id: '/_authenticated/returns/'
      path: '/returns'
      fullPath: '/returns/'
      preLoaderRoute: typeof AuthenticatedReturnsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/': {
      id: '/_authenticated/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movements/': {
      id: '/_authenticated/movements/'
      path: '/movements'
      fullPath: '/movements/'
      preLoaderRoute: typeof AuthenticatedMovementsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disbursement/': {
      id: '/_authenticated/disbursement/'
      path: '/disbursement'
      fullPath: '/disbursement/'
      preLoaderRoute: typeof AuthenticatedDisbursementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/destocking/': {
      id: '/_authenticated/destocking/'
      path: '/destocking'
      fullPath: '/destocking/'
      preLoaderRoute: typeof AuthenticatedDestockingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/defective/': {
      id: '/_authenticated/defective/'
      path: '/defective'
      fullPath: '/defective/'
      preLoaderRoute: typeof AuthenticatedDefectiveIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/': {
      id: '/_authenticated/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof AuthenticatedBillingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/$id': {
      id: '/_authenticated/sales/$id'
      path: '/sales/$id'
      fullPath: '/sales/$id'
      preLoaderRoute: typeof AuthenticatedSalesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/returns/new': {
      id: '/_authenticated/returns/new'
      path: '/returns/new'
      fullPath: '/returns/new'
      preLoaderRoute: typeof AuthenticatedReturnsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/new': {
      id: '/_authenticated/purchase-orders/new'
      path: '/purchase-orders/new'
      fullPath: '/purchase-orders/new'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/$id': {
      id: '/_authenticated/purchase-orders/$id'
      path: '/purchase-orders/$id'
      fullPath: '/purchase-orders/$id'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/$id': {
      id: '/_authenticated/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthenticatedProductsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movements/new': {
      id: '/_authenticated/movements/new'
      path: '/movements/new'
      fullPath: '/movements/new'
      preLoaderRoute: typeof AuthenticatedMovementsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disbursement/new': {
      id: '/_authenticated/disbursement/new'
      path: '/disbursement/new'
      fullPath: '/disbursement/new'
      preLoaderRoute: typeof AuthenticatedDisbursementNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/destocking/new': {
      id: '/_authenticated/destocking/new'
      path: '/destocking/new'
      fullPath: '/destocking/new'
      preLoaderRoute: typeof AuthenticatedDestockingNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/defective/new': {
      id: '/_authenticated/defective/new'
      path: '/defective/new'
      fullPath: '/defective/new'
      preLoaderRoute: typeof AuthenticatedDefectiveNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/settings': {
      id: '/_authenticated/billing/settings'
      path: '/billing/settings'
      fullPath: '/billing/settings'
      preLoaderRoute: typeof AuthenticatedBillingSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/new': {
      id: '/_authenticated/billing/new'
      path: '/billing/new'
      fullPath: '/billing/new'
      preLoaderRoute: typeof AuthenticatedBillingNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/$id': {
      id: '/_authenticated/billing/$id'
      path: '/billing/$id'
      fullPath: '/billing/$id'
      preLoaderRoute: typeof AuthenticatedBillingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedCashSessionsRoute: typeof AuthenticatedCashSessionsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedWarehousesRoute: typeof AuthenticatedWarehousesRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedBillingIdRoute: typeof AuthenticatedBillingIdRoute
  AuthenticatedBillingNewRoute: typeof AuthenticatedBillingNewRoute
  AuthenticatedBillingSettingsRoute: typeof AuthenticatedBillingSettingsRoute
  AuthenticatedDefectiveNewRoute: typeof AuthenticatedDefectiveNewRoute
  AuthenticatedDestockingNewRoute: typeof AuthenticatedDestockingNewRoute
  AuthenticatedDisbursementNewRoute: typeof AuthenticatedDisbursementNewRoute
  AuthenticatedMovementsNewRoute: typeof AuthenticatedMovementsNewRoute
  AuthenticatedProductsIdRoute: typeof AuthenticatedProductsIdRoute
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedPurchaseOrdersIdRoute: typeof AuthenticatedPurchaseOrdersIdRoute
  AuthenticatedPurchaseOrdersNewRoute: typeof AuthenticatedPurchaseOrdersNewRoute
  AuthenticatedReturnsNewRoute: typeof AuthenticatedReturnsNewRoute
  AuthenticatedSalesIdRoute: typeof AuthenticatedSalesIdRoute
  AuthenticatedBillingIndexRoute: typeof AuthenticatedBillingIndexRoute
  AuthenticatedDefectiveIndexRoute: typeof AuthenticatedDefectiveIndexRoute
  AuthenticatedDestockingIndexRoute: typeof AuthenticatedDestockingIndexRoute
  AuthenticatedDisbursementIndexRoute: typeof AuthenticatedDisbursementIndexRoute
  AuthenticatedMovementsIndexRoute: typeof AuthenticatedMovementsIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedPurchaseOrdersIndexRoute: typeof AuthenticatedPurchaseOrdersIndexRoute
  AuthenticatedReturnsIndexRoute: typeof AuthenticatedReturnsIndexRoute
  AuthenticatedSalesIndexRoute: typeof AuthenticatedSalesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedCashSessionsRoute: AuthenticatedCashSessionsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedWarehousesRoute: AuthenticatedWarehousesRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedBillingIdRoute: AuthenticatedBillingIdRoute,
  AuthenticatedBillingNewRoute: AuthenticatedBillingNewRoute,
  AuthenticatedBillingSettingsRoute: AuthenticatedBillingSettingsRoute,
  AuthenticatedDefectiveNewRoute: AuthenticatedDefectiveNewRoute,
  AuthenticatedDestockingNewRoute: AuthenticatedDestockingNewRoute,
  AuthenticatedDisbursementNewRoute: AuthenticatedDisbursementNewRoute,
  AuthenticatedMovementsNewRoute: AuthenticatedMovementsNewRoute,
  AuthenticatedProductsIdRoute: AuthenticatedProductsIdRoute,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedPurchaseOrdersIdRoute: AuthenticatedPurchaseOrdersIdRoute,
  AuthenticatedPurchaseOrdersNewRoute: AuthenticatedPurchaseOrdersNewRoute,
  AuthenticatedReturnsNewRoute: AuthenticatedReturnsNewRoute,
  AuthenticatedSalesIdRoute: AuthenticatedSalesIdRoute,
  AuthenticatedBillingIndexRoute: AuthenticatedBillingIndexRoute,
  AuthenticatedDefectiveIndexRoute: AuthenticatedDefectiveIndexRoute,
  AuthenticatedDestockingIndexRoute: AuthenticatedDestockingIndexRoute,
  AuthenticatedDisbursementIndexRoute: AuthenticatedDisbursementIndexRoute,
  AuthenticatedMovementsIndexRoute: AuthenticatedMovementsIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedPurchaseOrdersIndexRoute: AuthenticatedPurchaseOrdersIndexRoute,
  AuthenticatedReturnsIndexRoute: AuthenticatedReturnsIndexRoute,
  AuthenticatedSalesIndexRoute: AuthenticatedSalesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
